
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestao_vagas
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
security:
  token:
    secret: "TECHSOLUTIONS#123#123"
    expiration-hours: 2